messages:
  prefix: '&8[&6TitanTools&8] &7'
  no-permission: '&cYou don''t have permission to use this command!'
  player-not-found: '&cPlayer not found!'
  tool-given: '&aGave {player} a {tool}!'
  tool-received: '&aYou received a {tool}!'



smelter-pickaxe:
  enabled: true
  enchantments: []

lumberjack-axe:
  enabled: true
  check-leaves: true
  max-tree-height: 32
  enchantments: []

explosive-pickaxe:
  enabled: true
  debug-mode: true

  allowed-regions:
    - mine
    - wood
    - mastermind
    - enforcer
    - wiseguy
    - underboss
    - hitman
    - prestige
  enchantments: []

block-pickaxe:
  enabled: true
  minimum-drops-for-block: 2
  enchantments: []

bountiful-pickaxe:
  enabled: true
  scan-radius: 1
  enchantments: []



lightning-pickaxe:
  enabled: true
  proc-chance: 0.05
  enchantments: []

keyfinder-pickaxe:
  enabled: true
  key-chance: 0.0005
  titan-key-chance: 0.00005
  enchantments: []

currency-pickaxe:
  enabled: true
  activation-chance: 0.005
  rain-duration: 10
  money-chance: 0.15
  token-chance: 0.10
  ticket-chance: 0.10
  enchantments: []

nitro-pickaxe:
  enabled: true
  proc-chance: 0.03
  enchantments: []

rebirth-pickaxe:
  enabled: true
  proc-chance: 0.001
  enchantments: []



swiftcaster-rod:
  enabled: true
  enchantments: []

hellfire-rod:
  enabled: true
  enchantments: []



titan-rod:
  enabled: true
  point-chance: 0.01
  double-chance: 0.003
  enchantments: []

ticket-rod:
  enabled: true
  chance: 0.25
  enchantments: []

token-rod:
  enabled: true
  chance: 0.25
  enchantments: []

crate-rod:
  enabled: true
  key-chance: 0.05
  enchantments: []

lightning-rod:
  enabled: true
  strike-chance: 0.15
  enchantments: []